# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Thinking Agility
tagline:          'A way of thinking...'
description:      
url:              https://thinkingagility.github.io

author:
  name:           'Derrick Wheals'
  url:             https://thinkingagility.github.io

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           
